id: P000554
initial_creation_type: ocr
source_metadata:
  id: bdr:W27310
  title: ས་སྐྱའི་གདུང་རབས་ངོ་མཚར་རིན་ཆེན་ཀུན་འཕེལ
  author: ''
  volumes:
    07073854380a494ba0ccd3da9a95fa6e:
      image_group_id: I4279
      title: ''
      volume_number: 1
      total_pages: 878
      base_file: v001.txt
ebook_metadata:
  title: ས་སྐྱའི་གདུང་རབས་ངོ་མཚར་རིན་ཆེན་ཀུན་འཕེལ
  author: ''
  sku: P000554
  cover: cover.jpg
  layers:
  - pagination
